# -*- mode: ruby -*-
# vi: set ft=ruby :

$script = <<-SCRIPT
sudo yum install epel-release mc -y &&
sudo yum install mdadm iotop htop sysstat -y
SCRIPT

$script2 = <<-SCRIPT
sudo -s &&
mkdir /raid6 &&
mdadm --create /dev/md6 --level=6 --raid-devices=5 /dev/sdb /dev/sdc /dev/sdd /dev/sde /dev/sdf &&
parted --script /dev/md6 mklabel gpt


#mkfs.ext4 /dev/md6
#mount /dev/md6 /raid6
SCRIPT

Vagrant.configure("2") do |config|
 
  config.vm.box = "centos/7"
    config.vm.provision "shell", inline: $script
    config.vm.provision "shell", inline: $script2
    
  config.vm.provider "virtualbox" do |v|
  
  file_to_disk = 'disk2.vdi'
    unless File.exist?(file_to_disk)
          v.customize ['createhd', '--filename', file_to_disk, '--size', '10500']
          v.customize ["storagectl", :id, "--name", "SATA Controller", "--add", "sata"]
    end
    v.customize ['storageattach', :id, '--storagectl', 'SATA Controller', '--port', 1, '--device', 0, '--type', 'hdd', '--medium', file_to_disk]

    file_to_disk = 'disk3.vdi'
    unless File.exist?(file_to_disk)
          v.customize ['createhd', '--filename', file_to_disk, '--size', '10500']
    end
    v.customize ['storageattach', :id, '--storagectl', 'SATA Controller', '--port', 2, '--device', 0, '--type', 'hdd', '--medium', file_to_disk]
    
    file_to_disk = 'disk4.vdi'
    unless File.exist?(file_to_disk)
          v.customize ['createhd', '--filename', file_to_disk, '--size', '10500']
    end
    v.customize ['storageattach', :id, '--storagectl', 'SATA Controller', '--port', 3, '--device', 0, '--type', 'hdd', '--medium', file_to_disk]
    
    file_to_disk = 'disk5.vdi'
    unless File.exist?(file_to_disk)
          v.customize ['createhd', '--filename', file_to_disk, '--size', '10500']
    end
    v.customize ['storageattach', :id, '--storagectl', 'SATA Controller', '--port', 4, '--device', 0, '--type', 'hdd', '--medium', file_to_disk]
 
    file_to_disk = 'disk6.vdi'
    unless File.exist?(file_to_disk)
          v.customize ['createhd', '--filename', file_to_disk, '--size', '10500']
    end
    v.customize ['storageattach', :id, '--storagectl', 'SATA Controller', '--port', 5, '--device', 0, '--type', 'hdd', '--medium', file_to_disk]
 
 end
  
  
end
