filebeat.inputs:
- type: log
  enabled: true
  paths:
    - /var/log/nginx/*-access.log
  fields:
    type: nginx_access
  fields_under_root: true
  scan_frequency: 5s

- type: log
  enabled: true
  paths:
    - /var/log/nginx/*-error.log
  fields:
    type: nginx_error
  fields_under_root: true
  scan_frequency: 5s

- type: log
  enabled: true
  paths:
    - /var/log/firewald/*.log
  fields:
    type: firewalld_drop
  fields_under_root: true
  scan_frequency: 5s

- type: log
  enabled: true
  paths:
    - /var/log/bitrix/msmtp_default.log
  fields:
    type: b24-mail
  fields_under_root: true
  scan_frequency: 5s

output.logstash:
  hosts: ["192.168.1.231:5044"]
xpack.monitoring:
  enabled: true
  elasticsearch:
    hosts: ["http://192.168.1.231:9200"]
