---

- hosts: all
  become: true

  tasks:
    - name: Install epel-release
      dnf:
       name:
       - epel-release
       state: latest

    - name: Install nginx
      dnf:
       name:
       - nginx
       state: latest

    - name: Firewall rules service
      firewalld:
       service: "{{ item }}"
       permanent: true
       state: enabled
      with_items:
       - http
       - https
    
    - name: Firewall rules {{ ansible_hostname }}
      firewalld:
        port: "{{ item }}"
        permanent: true
        state: enabled
      with_items:
        - 8080/tcp

    - name: Starting the nginx
      service: name=nginx state=started enabled=yes
    
    - name: Starting the firewalld
      service: name=firewalld state=started enabled=yes
    
    - name: Firewall deploy rules
      shell: firewall-cmd --reload