---

- hosts: all
  become: true
  vars:
    nginx_listen_port: 8080

  tasks:
    - name: Install epel-release
      dnf:
       name:
       - epel-release
       state: latest

    - name: Install nginx
      dnf:
       name:
       - nginx
       state: latest

    - name: Firewall rules service
      firewalld:
       service: "{{ item }}"
       permanent: true
       state: enabled
      with_items:
       - http
       - https
    
    - name: nginx conf j2
      template:
        src: nginx.conf.j2
        dest: /etc/nginx/nginx.conf
      notify:
        - reload nginx

    - name: Firewall rules {{ ansible_hostname }}
      firewalld:
        port: "{{ item }}"
        permanent: true
        state: enabled
      with_items:
        - 8080/tcp

    - name: Starting the nginx
      service: name=nginx state=started enabled=yes
    
    - name: Starting the firewalld
      service: name=firewalld state=started enabled=yes
    
    - name: Firewall deploy rules
      shell: firewall-cmd --reload

  handlers:
    - name: reload nginx
      service: name=nginx state=reloaded