# -*- mode: ruby -*-
# vi: set ft=ruby :


Vagrant.configure("2") do |config|

  config.vm.box = "centos/7"
    config.vm.provision "shell", inline: $script
    config.vm.provision "shell", inline: $script2

  config.vm.provider "virtualbox" do |v|


end
